import {
  Search,
  PencilRuler,
  Truck,
  Wrench,
  ShieldCheck,
  Headset,
  ClipboardCheck,
  Package,
  RefreshCw,
  PhoneCall,
  Mail,
  MessageSquare,
  CalendarCheck,
  CheckCircle2,
  Building2,
  Rocket,
  type LucideIcon,
} from "lucide-react";
import type { IconName } from "@/data/pageContent";

export const iconMap: Record<IconName, LucideIcon> = {
  search: Search,
  pencil: PencilRuler,
  truck: Truck,
  wrench: Wrench,
  shield: ShieldCheck,
  headset: Headset,
  clipboard: ClipboardCheck,
  package: Package,
  refresh: RefreshCw,
  phone: PhoneCall,
  mail: Mail,
  message: MessageSquare,
  calendar: CalendarCheck,
  check: CheckCircle2,
  building: Building2,
  rocket: Rocket,
};
